source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'JLDishwashers' do
    pod 'Alamofire', '~> 3.4'
    pod 'AlamofireImage', '~> 2.0'
    pod 'AlamofireObjectMapper', '~> 3.0'
end